### ISSUE TITLE
Error while logging in using name and password

### ISSUE THREAD

**Issue by shree675** [Dev-CasperTheGhost/pastebin-api#74]
On executing the following code:
```ts
const client = new PasteClient(process.env.PASTEBIN_DEV_KEY ?? "");

const token = await client.login(process.env.PASTEBIN_USERNAME ?? "", process.env.PASTEBIN_PASSWORD ?? "").catch((err) => {
  console.error(err);
});
console.log(token);
```

It gives the following error:
```
Error: Not supported
                      at fetch (D:\CLI Tools\Markdown-HTML Generator\node_modules\pastebin-
api\dist\index.js:36:31)
                      at PasteClient.login (D:\CLI Tools\Markdown-HTML Generator\node_modules\pastebin-
api\dist\index.js:166:23)
                      at D:\CLI Tools\Markdown-HTML Generator\lib\commands\init.js:92:22
                      at step (D:\CLI Tools\Markdown-HTML Generator\lib\commands\init.js:33:23)
                      at Object.next (D:\CLI Tools\Markdown-HTML Generator\lib\commands\init.js:14:53)
                      at D:\CLI Tools\Markdown-HTML Generator\lib\commands\init.js:8:71
                      at new Promise (<anonymous>)
                      at __awaiter (D:\CLI Tools\Markdown-HTML Generator\lib\commands\init.js:4:12) 
                      at Command.init (D:\CLI Tools\Markdown-HTML Generator\lib\commands\init.js:86:33)
                      at Command.listener [as _actionHandler] (D:\CLI Tools\Markdown-HTML Generator\node_modules\commander\lib\command.js:488:17)
```

Note that ```process.env.PASTEBIN_DEV_KEY```, ```process.env.PASTEBIN_USERNAME``` and ```process.env.PASTEBIN_PASSWORD``` are all defined (non-null).

Please provide solution to this issue at your earliest convenience. Also let me know if I am doing something wrong.

**Comment by Dev-CasperTheGhost** [comment]
What version of node are you using?

**Comment by shree675** [comment]
v12.16.0

**Comment by Dev-CasperTheGhost** [comment]
All works fine for me, can you try upgrade your node version?

**Comment by shree675** [comment]
There's actually a problem with my computer. If I upgrade my node version higher than this, nodejs will not work. I keep getting SSL errors.
Is there any other workaround to this? What if I downgrade the version of **pastebin-api**?

**Comment by shree675** [comment]
Hey, I downgraded the version of **pastebin-api** to ```^1.0.6``` and it worked.
For now, I'll settle with this workaround. Thanks.
